# -*- coding: utf-8 -*-
"""myowncodestreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hm1WR1YazZnCcmp98Xhfps6v3o_lobo4
"""

# prompt: python code for  a dashboard

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample data (replace with your actual data)
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [100, 120, 150, 130, 180, 200],
    'Expenses': [80, 90, 100, 110, 120, 130]
}
df = pd.DataFrame(data)

# Dashboard title
st.title("Sales & Expenses Dashboard")

# Display the DataFrame
st.subheader("Data")
st.dataframe(df)

# Line chart for Sales and Expenses
st.subheader("Sales and Expenses Trend")
fig, ax = plt.subplots()
sns.lineplot(x='Month', y='Sales', data=df, label='Sales', ax=ax)
sns.lineplot(x='Month', y='Expenses', data=df, label='Expenses', ax=ax)
plt.xlabel("Month")
plt.ylabel("Amount")
plt.title("Sales and Expenses Trend")
st.pyplot(fig)

# Bar chart for Sales
st.subheader("Sales by Month")
fig, ax = plt.subplots()
sns.barplot(x='Month', y='Sales', data=df, ax=ax)
plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("Sales by Month")
st.pyplot(fig)

# KPIs (Key Performance Indicators)
st.subheader("Key Performance Indicators")
total_sales = df['Sales'].sum()
st.metric("Total Sales", total_sales)
avg_sales = df['Sales'].mean()
st.metric("Average Sales", avg_sales)

# You can add more charts, tables, and widgets as per your needs
# For example:
# - Pie chart for sales distribution by product category
# - Interactive widgets for filtering data
# - Maps to show location-based data
# - Download buttons for data

# To run this dashboard, save it as a Python file (e.g., dashboard.py)
# Then, run the following command in your terminal:
# streamlit run dashboard.py